name: deploy

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12 

        with:

          region: "eu"

          branch: "master"

          usedocker: true

          stack: "container"

          heroku_app_name: "Sakuramirrorbotrepo1" 

          docker_heroku_process_type: worker

          heroku_email: "anjali.3008@rediffmail.com"

          heroku_api_key: "26a27b91-2e9d-41d9-bcfb-e87f65ab31ba"
